### ISSUE TITLE
Option to not be @'d in the comments

### ISSUE THREAD

**Issue by jagregory** [OP5dev/TF-via-PR#364]
#### Is your feature request related to a problem

I have a lot of Terraform matrix jobs and when they run in a PR I get @'d in the comments... _a lot_.

#### Describe the solution you'd like

It'd be awesome if I could disable @'ing in the action, so I don't get spammed with notifications when my PRs run.

#### Describe alternatives you've considered

Turning my phone off. 😆

**Comment by rdhar** [comment]
Thanks @jagregory, this issue/request is way too relatable!

Trying to figure how best to address it:

- Simplest would be to add something like a "mention-author" option to toggle @'ing. But that's yet another input parameter to add to the list. 
- Alternatively, add an option to specify the line like, "By <author> at <timestamp> (<link>)". BUT that's still another input parameter, and way more complex to interpolate! 
- Got some other ideas? 

As an aside, would you mind sharing a little more about your experience with this Action? External feedback is rare, especially from matrix users, so keen to know how you're getting along.

**Comment by jagregory** [comment]
I have one pipeline which can sometimes trigger up-to 40 matrixed terraform jobs 😅 

I was thinking the first option would be the simplest, just template the inclusion/exclusion of the `@` in the message body so the author doesn't get tagged. Anything more than that feels like it would get complicated quite quickly.

As for feedback, it's been a very helpful action and I tried a couple of alternatives but found this one the easiest to use and produces the most useful output. I particularly like the short summary of changes which is great for an at-a-glance look, and the inclusion of a diff as well so I don't have to pour over the full plan to understand what's changing. Specifically for matrix use: I don't love that there's a comment created per job but I understand why that is. If there was a way to "fan-in" after a matrix job to post a single summary comment that would be amazing, but I think that's a lot of complexity and might not be worth the effort.

Thinking out loud (and back to the original issue) perhaps an option to only tag the author in a comment when a diff has changes? That would be probably be more useful than just disabling the tagging entirely. Or possibly a variation on #361 but more about posting comments than uploading plans.

**Comment by rdhar** [comment]
Happy to share this has been shipped with [v13.0.0](https://github.com/OP5dev/TF-via-PR/releases/tag/v13.0.0), where your contribution has been credited!

Please consider ⭐ this project, if you find it useful.

[![GitHub repository stargazers](https://img.shields.io/github/stars/devsectop/tf-via-pr)](https://github.com/devsectop/tf-via-pr "Become a stargazer.")

---

- For your original request, you can either set `tag-actor: on-change` to only be tagged upon diff/error, or `never` to prevent tagging altogether (default is `always`).
- For the follow-up request, you can either set `comment-pr: on-change` to only add PR comment upon diff/error, or `never` to avoid commenting altogether (default is `always`).
- While matrix summary is currently out-of-scope, I wonder if the 1-line summary in the PR status checks are of use to you (screenshot attached), or even the workflow summary page?

![Image](https://github.com/user-attachments/assets/bdd40419-ca62-42ab-949e-af6be78e96ab)
