### ISSUE TITLE
actions referencing tf-via-pr failing with "Unable to resolve action. Repository not found"

### ISSUE THREAD

**Issue by bvs-langchain** [OP5dev/TF-via-PR#367]
#### Describe the bug

Actions referencing tf-via-pr are now failing, appears to be due to change in name to `OP5dev`:

```
Prepare all required actions
Getting action download info
Error: Unable to resolve action. Repository not found: devsectop/tf-via-pr
```

#### To Reproduce

Follow the quickstart: https://github.com/OP5dev/TF-via-PR?tab=readme-ov-file#how-to-get-started-quickly

#### Expected behavior

action should successfully be resolved at the old location.

**Comment by rdhar** [comment]
Happy to share this has been shipped with [v13.0.0](https://github.com/OP5dev/TF-via-PR/releases/tag/v13.0.0), where your contribution has been credited!

Please consider ⭐ this project, if you find it useful.

[![GitHub repository stargazers](https://img.shields.io/github/stars/devsectop/tf-via-pr)](https://github.com/devsectop/tf-via-pr "Become a stargazer.")

---

While it's unclear how/if GitHub will forward action references after the [name change](https://github.com/orgs/OP5dev/discussions/7), I don't suppose there's much else to do than plough ahead with new releases (and keep breaking changes to a minimum!)
